version: '3'

services:
  risevest:
    build: .
    image: risevest
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '3000:${PORT}'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  db:
    image: mariadb
    restart: always
    ports:
      - '6603:6603'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql

volumes:
  redis-data:
